# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KBLive' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for KBLive

pod 'AFNetworking'
pod 'SVProgressHUD'
pod 'Masonry'
pod 'MJExtension'
pod 'MJRefresh'
pod 'SDWebImage'
pod 'LFLiveKit'








  target 'KBLiveTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KBLiveUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
